apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostpath:
    path: /temp/data/pv-1

---

apiVersion: v1
kind: persistentVolume
metadata:
  name: local-pv-2
  laabels:
    type: local
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteOnce
    hostpath:
      path: /temp/data/pv-2       
